# Generated by Django 4.0.4 on 2022-05-13 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0001_initial'),
        ('voto', '0001_initial'),
        ('candidato', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='candidato',
            new_name='candidate',
        ),
    ]
