# Generated by Django 4.0.4 on 2022-05-13 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleicao', '0001_initial'),
        ('candidato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='voto',
            fields=[
                ('cpf', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('candidatoPleito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidato.candidato')),
                ('eleicaoPleito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleicao.eleicao')),
            ],
        ),
    ]
