# Generated by Django 4.0.4 on 2022-05-13 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0002_rename_eleicao_election'),
        ('candidato', '0002_rename_candidato_candidate'),
        ('voto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='voto',
            new_name='vote',
        ),
    ]
