# Generated by Django 4.0.4 on 2022-05-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='eleicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomePleito', models.CharField(max_length=50)),
                ('dataInicial', models.DateField()),
                ('dataFinal', models.DateField()),
                ('quantidadeCandidatos', models.IntegerField()),
                ('candidatos', models.ManyToManyField(to='candidato.candidato')),
            ],
        ),
    ]
